services:
  postgres:
    container_name: Notes
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: NotesDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: